version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: app
    ports:
      - 5439:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
